### ISSUE TITLE
CRITICAL: DON'T USE Leaking user credentials to `https://api.r2explorer.dev/api/releases/latest/`

### ISSUE THREAD

**Issue by canuc** [G4brym/R2-Explorer#49]
There is no reason for this client to pass basic auth creds to check the latest version for the frontend. 

If the creator is a bad actor, then they will have the basic auth credentials of any user that logs in.

I see a request on the front end that carries basic auth credentials to: `https://api.r2explorer.dev/api/releases/latest/`.

Please don't use until this issue is fixed.

**Comment by G4brym** [comment]
Hey there, i just disabled the update checker and pushed it to everyone using the default dashboard.

The bug here was that when you log onto a basic auth server, I'm defining the `Authentication` header as default in axios ([source here](https://github.com/G4brym/R2-Explorer/blob/main/packages/dashboard/src/store/index.js#L169)), and this was the reason the auth token were being sent to that url.

If you are concerned with authentication, you should definitely enable Cloudflare Access on your instance [docs here](https://r2explorer.dev/getting-started/security/#authenticating-with-cloudflare-access).

**Comment by G4brym** [comment]
Thanks for reporting this issue, I'm closing it as the fix has already been pushed, feel free to open another one if you find anything else
